# Place all the behaviors and hooks related to the matching controller here.
# All this logic will automatically be available in application.js.
# You can use CoffeeScript in this file: http://coffeescript.org/

$ ->
$('#cover-image').click ->
  $('#article_image').click()
  false
  # must!

# ---
# generated by js2coffee 2.2.0
